---
# Default variables to configure certificate requests
certificate_requests: [] # noqa: var-naming[no-role-prefix]
# default variables to limit execution at runtime
cert_action: "{{ item.cert_action }}" # noqa: var-naming[no-role-prefix]
kdb_id: "{{ item.kdb_id }}" # noqa: var-naming[no-role-prefix]
