---
# Default variables for confiuratino of runtime components
resource_id: "{{ item.resource_id }}"  # noqa: var-naming[no-role-prefix]
stanza_id: "{{ item.stanza_id }}"  # noqa: var-naming[no-role-prefix]
entry_id: ""  # noqa: var-naming[no-role-prefix]
