---
- name: Configure rate limiting policies [-e action=
    [add|delete|rename|update|export_file|import_file|get_all|get]
    -e name=<rate_limiting_policy_name> -e file=<path/to/import/or/export/file.yaml>]
  ibm.isam.isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.rate_limiting.{{ item.action | default('import_file') }}
    isamapi: "{{ item | ibm.isam.exclude('action')
              | combine({'filename': (homedir + '/' + item.filename)} if (item.filename is defined) else {})
              | combine({'id': item.filename | basename} if (item.filename is defined) else {}) | default(omit) }}"
  loop: "{{ web_ratelimiting_policies }}"
  when:
    - item is defined
  notify: Commit Changes
