---
# Default variables to configure signer certificates
signer_certificates: [] # noqa: var-naming[no-role-prefix]
# default variables to limit execution at runtime
cert_action: "{{ item.cert_action }}" # noqa: var-naming[no-role-prefix]
kdb_id: "{{ item.kdb_id }}" # noqa: var-naming[no-role-prefix]
label: "{{ item.label if (item.label is defined) }}" # noqa: var-naming[no-role-prefix]
cert_id: "{{ item.cert_id if (item.cert_id is defined) }}" # noqa: var-naming[no-role-prefix]
