---
# Default variables for configuration of reverse proxy instances
instances: []  # noqa: var-naming[no-role-prefix]
# variables to control whether to configure one instance and/or a specific stanza at a time or everything from the configurations
inst_name: "{{ item.0.inst_name }}"  # noqa: var-naming[no-role-prefix]
stanza_id: "{{ item.1.stanza_id }}"  # noqa: var-naming[no-role-prefix]
method: "{{ item.1.method }}"  # noqa: var-naming[no-role-prefix]
entry_id: "{{ item.1.entry_id if item.1.entry_id is defined else '' }}"  # noqa: var-naming[no-role-prefix]
