---
# Default for Policy
admin_id: "{{ sec_master_id | default('sec_master') }}" # noqa: var-naming[no-role-prefix]
admin_pwd: "{{ sec_master_pwd }}" # noqa: var-naming[no-role-prefix]
admin_domain: Default # noqa: var-naming[no-role-prefix]

# Verbosity
# debug_verbosity: 2 # noqa: var-naming[no-role-prefix]
