---
# Default variables for creation of reverse proxy instances
instances: []  # noqa: var-naming[no-role-prefix]
# limit execution at runtime to filter for inst_name's
inst_name: "{{ item.inst_name }}"  # noqa: var-naming[no-role-prefix]
