---

# default variables to create password for system accounts
sysaccounts: [] # noqa: var-naming[no-role-prefix]
# limit execution at runtime to filter for system accounts
id: "{{ item.id }}" # noqa: var-naming[no-role-prefix]
