---

# Provide a valid SMTP collector server name
add_system_alerts_smtpServer: # noqa: var-naming[no-role-prefix]
add_system_alerts_smtpPort: 25 # noqa: var-naming[no-role-prefix]
add_system_alerts_from_email: # noqa: var-naming[no-role-prefix]
add_system_alerts_to_email: # noqa: var-naming[no-role-prefix]
