---
# default variables for installing multiple fix packs
fix_packs: [] # noqa: var-naming[no-role-prefix]
# limit the to be installed fix packs at runtime
file: "{{ item.file }}" # noqa: var-naming[no-role-prefix]
filename: "{{ item.file | basename }}" # noqa: var-naming[no-role-prefix]

# Default homedir.  This defaults to inventory_dir for backwards compatibility reasons,
#  even though the inventory_dir should NEVER be used to store files (should basically only contain files that can be parsed by an inventory_plugin)
#  a better default value for homedir, would be playbook_dir:
#       `homedir: "{{ playbook_dir }}"`
#  Set to "" , to be able to define a file relative from your project directory
#
homedir: "" # noqa: var-naming[no-role-prefix]
