---
# Default variables for configuration of access control policy attachments
admin_id: "{{ sec_master_id | default('sec_master') }}" # noqa: var-naming[no-role-prefix]
admin_pwd: "{{ sec_master_pwd }}" # noqa: var-naming[no-role-prefix]
admin_domain: Default # noqa: var-naming[no-role-prefix]
