---
# default variables for installing multiple fix packs
updates: [] # noqa: var-naming[no-role-prefix]
# limit the to be installed fix packs at runtime
file: "{{ item.file }}" # noqa: var-naming[no-role-prefix]
filename: "{{ item.file | basename }}" # noqa: var-naming[no-role-prefix]
